### PR TITLE
Fixes outdated mapping for the Go editor (goclipse)

### PR DESCRIPTION
**Pull request by steve-perkins**
Support for Go (via the ["goclipse" plugin](https://github.com/GoClipse/goclipse)) has been broken in "eclipse-color-theme" for some time, due to outdated mappings.  Quite awhile back, the plugin ID for "goclipse" changed to "`com.googlecode.goclipse.ui`", and the "`pluginKey`" elements inside of the mapping file also changed (dropping the "`_color`" suffix).

This pull request simply updates the mapping file, to reflect the new plugin ID and pluginKey names.  Discussion of the issue can be found in this "goclipse" project mailing list thread:  https://groups.google.com/forum/#!topic/goclipse/iO1wfn4ovbc.

Thanks!

### CODE REVIEW

**Comment by fhd** [comment]
Thanks for the PR - and sorry for the delay :disappointed:

I'll happily merge it, just one question: Wouldn't it make sense to keep both mappings around to support the old version of Goclipse? (That's assuming it's still used by a non-trivial number of people, I have no idea.)

**Comment by steve-perkins** [comment]
Haha... sorry for my own delay in responding!  I've been traveling recently.

I considered leaving both versions in there.  My primary career language is Java, and so I'm very much wired for backwards compatibility, and accustomed to the needs of slow-moving enterprise shops.  However, Go by comparison is such a young programming language, and such a fast-moving target.  This breaking change was made on the Goclipse side well over two years ago, and I can't even *conceive* of someone keeping a Go environment un-updated for that long (that was 4 major releases ago).

So I'm more than glad to put the old files back in there if you'd prefer, but in 2015 I really think it would be a matter of cruft rather than legacy support.

**Comment by thenickdude** [comment]
This fix is great, thanks, I was worried I might have to switch back to the Light theme!

It looks like goclipse also (now) needs mappings for [these symbols](https://github.com/GoClipse/goclipse/blob/16876e43bc175640e17bd2ef06297c290dabce31/plugin_ide.ui/src/com/googlecode/goclipse/ui/text/GoColorPreferences.java):

`syntax_highlighting_operator` map to `operator`
`syntax_highlighting_syntax_chars` map to `bracket`
`syntax_highlighting_character` map to `string`

**Comment by fhd** [comment]
Sorry for another delay! Merged now. Sure, no need to keep the old stuff around if it's unlikely that anyone is still on that version.

**Pull request closed without merging**
